### ISSUE TITLE
user.css?

### ISSUE THREAD

**Issue by helmut72** [Kdecherf/shaarli-hacker#1]
Would be cool if you upload your user.css. Looks great 😎

**Comment by Kdecherf** [comment]
Fixed by 3e9a1b8146f50e709c1faa662ec57be0efa27f82, enjoy :)

**Comment by helmut72** [comment]
thanks 👍

**Comment by helmut72** [comment]
Wanted to try it out, copied folder "hacker" to folder "tpl", but then Shaarli crashed:

```
An unexpected error happened, and the error template could not be displayed.

Template error not found!
/var/www/html/inc/rain.tpl.class.php268
#0 /var/www/html/inc/rain.tpl.class.php(164): RainTPL->check_template()
#1 /var/www/html/application/render/PageBuilder.php(253): RainTPL->draw()
#2 /var/www/html/application/front/controller/visitor/ShaarliVisitorController.php(66): Shaarli\Render\PageBuilder->render()
#3 /var/www/html/application/front/controller/visitor/ErrorController.php(45): Shaarli\Front\Controller\Visitor\ShaarliVisitorController->render()
#4 [internal function]: Shaarli\Front\Controller\Visitor\ErrorController->__invoke()
#5 /var/www/html/vendor/slim/slim/Slim/App.php(728): call_user_func_array()
#6 /var/www/html/vendor/slim/slim/Slim/App.php(396): Slim\App->handlePhpError()
#7 /var/www/html/vendor/slim/slim/Slim/App.php(297): Slim\App->process()
#8 /var/www/html/index.php(176): Slim\App->run()
#9 {main}
```

Is there something else needed? I use Shaarli 0.12.1

Thanks.

**Comment by Kdecherf** [comment]
@helmut72 I don't think the template works with shaarli 0.12, I stayed on 0.11 on my instance
